### ISSUE TITLE
ClangFormat

### ISSUE THREAD

**Issue by alexfish** [ustwo/objective-c-style-guide#5]
Would be good to create a config for this based on the style guide 

https://github.com/travisjeffery/ClangFormat-Xcode

**Comment by martinstolz** [comment]
ClangFormat does not give us enough freedom to recreate our style guide, though I'd be willing to give up some parts of our style guide and have this auto format in place.

**Comment by iceydee** [comment]
My main issue with clangformat is that it's terrible at handling blocks. It doesn't properly understand them I'm guessing.

I also had to disable ClangFormat for Dice because I kept getting pizza-balled (at one point my computer was running at 85-degrees because of it!).

Give them a year to get everything fixed and we can have another go.

**Comment by alexfish** [comment]
Sounds like it's not yet up to scratch then, closing this down.
